### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by dadkins20** [CKwan-hub/JSButtonHW#2]
I found three bugs in your code that you didn't quite account for.  

1. If you click button 3 multiple times then it just makes the countdown faster.  You should prevent it from doing multiple intervals.

2. If the bomb blows up, the timer keeps counting into the negatives.

3. If you press button 3, then disarm it with button 4 it works.  But if you press button 3 again, the timer starts from where you last left off.

Nice work overall!  See if you can fix these before Thursday.

**Comment by CKwan-hub** [comment]
Oddly enough, numbers 1&2 are related. I'm using the "--" for countdown
from 10, and the faster speed also causes the negatives. If button three is
pressed once on it's own, it will correctly stop at 0, and do the 4 actions
at completion. However, the additional presses seem to either (or both) add
another countdown simultaneously, and skip 0 which never triggers the End()
function.

Out of curiosity, did the button 3 press (when only pressed once) do all
the resulting actions correctly? That's where I really tried to pack in
features.

I had a great stretch of time at work to write all this today, and I'll
take a look tomorrow morning for adding a reset & simultaneous countdown
prevention.

**Comment by dadkins20** [comment]
Yes, it worked perfectly when I first tried it.  I specifically tried to break it after it was successful the first time.

**Comment by CKwan-hub** [comment]
Oh thank God, I just closed my laptop and if it didn't function at all, the
computer would have been right back open!

**Comment by CKwan-hub** [comment]
Fixed! 

1) Added a "cooldown" on button 3, So if already active, the button is disabled from running simultaneous countdowns. 
2) Fixed with problem 1, but in case there were ever further revisions that allow a non-refresh of the page to reset the "boom" (Currently it disables everything but the BOOM display and explosion image), the aforementioned cooldown is released after 9 seconds. 
3) Rectified with a specification that when beginning the Button 3 countdown, denoted "B3Countdown()", the counter = 10. This allows arms, disarm, arm, and so on with the counter resetting each time!
